#!/bin/bash

GITHUB_HOST=${STRAP_GITHUB_HOST:="github.com"}
GITHUB_USER=${STRAP_GITHUB_USER:="gr8routdoors"}

if [ ! -d "$HOME/.oh-my-zsh" ]; then
    echo "Installing oh-my-zsh..."
    sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

    echo "Looking to apply custom oh-my-zsh config from github..."
    cd $HOME/.oh-my-zsh/custom && git clone "https://$GITHUB_HOST/$GITHUB_USER/oh-my-zsh.git"

else
    echo "Checking for oh-my-zsh updates..."
    sh -c "$(cat $ZSH/tools/upgrade.sh)"

    echo "Refreshing custom oh-my-zsh config from github..."
    echo "Checking $GITHUB_HOST/$GITHUB_USER/oh-my-zsh.git"
    cd $HOME/.oh-my-zsh/custom && git pull
fi
