#!/bin/sh
# Run by Strap after installing Brewfile dependencies

cd $(dirname $0)/..

# The location to find the strap dotfiles and oh-my-zsh repos
export STRAP_GITHUB_HOST=${STRAP_GITHUB_HOST:="github.com"}
export STRAP_GITHUB_USER=${STRAP_GITHUB_USER:="gr8routdoors"}

# Support different settings for github enterprise
export GITHUB_HOST=${GITHUB_HOST:="github.com"}
export GITHUB_USER=${GITHUB_USER:=$STRAP_GITHUB_USER}

script/configure-hub
script/install-oh-my-zsh
script/install-sdkman
script/open-manual-step-docs
